### ISSUE TITLE
Something wrong when running

### ISSUE THREAD

**Issue by fanxy121** [ItoSchum/LINE_Blog_img_crawler#1]
At the step of choose mode will go error like:

  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 94, in <module>
    whole_parse_and_download(raw_url)
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 77, in whole_parse_and_download
    mono_article_parse(article)
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 67, in mono_article_parse
    downloadImg(imgURLs_article, article_name)
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 55, in downloadImg
    mkdir(folder_path)
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 40, in mkdir
    os.makedirs(path)
  File "C:\Program Files\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\Users\\Administrator/wholepage/2018-12-31 20:52 本年もお世話になりま

How to run it correctly.
Thank you,

**Comment by itoschum** [comment]
I’ll recommend try ‘C:\Users\Administrator\wholepage\2018-12-31 20:52 本年もお世話になりま’ as storing path instead, considering Windows’ path format.

**Comment by fanxy121** [comment]
As the following command line
C:\Users\Administrator>C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py

Please Input the URL: (e.g. https://lineblog.me/uesaka_sumire/archives/2018-11.html)
URL: https://lineblog.me/uesaka_sumire/archives/2018-12.html

Please Input the Saving Path: (e.g. ~/[YOUR_DIRNAME])
Path: c:\1

Please Choose Mode:
 0 --- Current Page Lateset Article Only
 1 --- Current Page Whole
 2 --- Current Month Whole
 3 --- Current Page with Specific Position
Mode: 0
Traceback (most recent call last):
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 91, in <module>
    specific_parse_and_download(raw_url)
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 86, in specific_parse_and_download
    mono_article_parse(articles[article_position])
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 67, in mono_article_parse
    downloadImg(imgURLs_article, article_name)
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 55, in downloadImg
    mkdir(folder_path)
  File "C:\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 40, in mkdir
    os.makedirs(path)
  File "C:\Program Files\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] 目录名称无效。: 'c:\\1\\2018-12-31 20:52 本年もお世話になりました&北海道スペシャル完結編'

Not the path fault

**Comment by ItoSchum** [comment]
How about trying a directory name without special characters such as space. Please try “C:\Users\Administrator\wholepage\sample\”

**Comment by itoschum** [comment]
Okay, I found that it's not allowed on Windows CMD to create a directory with colon included in the directory name. Please add this "folder_path = folder_path.replace(':', '-')" after line 54 of LineBlog_img_crawler.py, or try my latest commit. Thanks for your feedback.

**Comment by fanxy121** [comment]
no error 267 but display
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 95, in <module>
    whole_parse_and_download(raw_url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 78, in whole_parse_and_download
    mono_article_parse(article)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 68, in mono_article_parse
    downloadImg(imgURLs_article, article_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1\LineBlog_img_crawler.py", line 56, in downloadImg
    mkdir("%s", folder_path)
TypeError: mkdir() takes 1 positional argument but 2 were given

**Comment by itoschum** [comment]
My apology for my typo. I've modified the code as v1.1.1. Please check it out.

**Comment by fanxy121** [comment]
Thank you. The program works good.
But it only dl  the first  5 pages/15 archives  images

**Comment by itoschum** [comment]
Thanks for your feedback. I just updated "Mode 2" for dumping images of all related pages, please check it out. :)

**Comment by fanxy121** [comment]
Extremely grateful. It works very fine
The old archives images was beginning with http://line.blogimg.jp/userid/imgs/*** since oct.2016,That cannot be crawler.
After nov.2016 archives images was beginning with https://obs.line-scdn.net/***.
Maybe the difference of http&https due to old archives can't be crawler.

Traceback (most recent call last):
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 126, in <module>
    whole_parse_and_download(target_url)
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 103, in whole_parse_and_download
    mono_article_parse(article)
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 93, in mono_article_parse
    downloadImg(imgURLs_article, article_name)
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 83, in downloadImg
    uRetr(imgURL, folder_path + "/%03d.jpg" %imgID)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Program Files\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Program Files\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by itoschum** [comment]
I just tested it, which seemed working well on my laptop. Could you please give it another shot?

**Comment by fanxy121** [comment]
**It could be solve by out of Network blockade area**

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1.1\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 126, in <module>
    whole_parse_and_download(target_url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1.1\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 103, in whole_parse_and_download
    mono_article_parse(article)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1.1\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 93, in mono_article_parse
    downloadImg(imgURLs_article, article_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\LINE_Blog_img_crawler-1.1.1\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 83, in downloadImg
    uRetr(imgURL, folder_path + "/%03d.jpg" %imgID)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by itoschum** [comment]
I see. After all, the access to LINE Blog requires breaking the GFW.
