### ISSUE TITLE
Special words error

### ISSUE THREAD

**Issue by fanxy121** [ItoSchum/LINE_Blog_img_crawler#2]
When met some words like (*´꒳`*).It doesn't work
Traceback (most recent call last):
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 126, in <module>
    whole_parse_and_download(target_url)
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 103, in whole_parse_and_download
    mono_article_parse(article)
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 93, in mono_article_parse
    downloadImg(imgURLs_article, article_name)
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 81, in downloadImg
    mkdir(folder_path)
  File "C:\LINE_Blog_img_crawler-1-2\LineBlog_img_crawler.py", line 65, in mkdir
    os.makedirs(path)
  File "C:\Program Files\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\Administrator/2017\\2017-4-11 15-55 会社で(*´꒳`*)'

Any possibility to add Mode from this page to the end page(e.g. https://lineblog.me/user/archives/2017-04.html?p=31)

**Comment by itoschum** [comment]
Although it’s possible to replace the special character, I think I can add another mode getting rid of the article title as part of the directory name to observe Windows’ naming restrictions. And I just updated my repo, please check it out.

**Comment by fanxy121** [comment]
How to use the original name of images(e.g. https://obs.line-scdn.net/ **imageID**) instead of 000 001 when download

**Comment by itoschum** [comment]
I name it as serial number like '001' in the script, since the original image ID is meaningless and not useful for sorting.

**Comment by fanxy121** [comment]
When using crawler at step5 mode2 all related pages It will download all the article images but the first page image except.
eg:https://lineblog.me/tomomiitano/archives/2019-11.html 
Just get images from 2019/11/5 18:00 to 2019/11/1 13:35 No 2019/11/7 14:10 to 2019/11/5 19:25
Thanks for fix

**Comment by ItoSchum** [comment]
I found it is because these images stored on other websites (Facebook, Instagram, Twitter and even personal website) instead of LINE Blog itself. I'll try to improve my script, but it may take some time.

**Comment by itoschum** [comment]
Sorry for the significant delay, but it seems that the problem cannot be recurred now.
